# WARNING: mkdocs doesn't work with gh-pages activated
# Just don't activate github page then 'mkdocs gh-deploy --clean'

site_name: Knowledge Center
site_url: https://constellr.github.io/product-lst/
repo_url: https://github.com/constellr/product-lst
repo_name: constellr/product-lst

edit_uri: https://github.com/constellr/product-lst/tree/main/docs/
nav:
  - Home: index.md
  - Our Technology: our-technology.md
  - Product Portfolio: 
    - Constellr's product offer: Constellr-product-offer.md
    - Product deliverables: product-deliverables.md
    - Technical specifications: Technical-specification.md
  - Insights: use-cases.md
  - End User Platform Documentation:
    - UI documentation: UI-documentation.md
    - API documentation: API-documentation.md
  - Explorer Lab: demo.md
 

theme:
  name: material
  #show_toc: false
  #toc_depth: 1;
  favicon: assets/logo-constellr-dark-icon.svg
  logo: assets/logo-constellr-dark-icon.svg
  features:
    - toc.integrate
  text-align: right

  custom_dir: overrides

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css

strict: true

  
markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mike
  

extra:
  version:
    provider: mike

