# WARNING: mkdocs doesn't work with gh-pages activated
# Just don't activate github page then 'mkdocs gh-deploy --clean'

site_name: Documentation
site_url: https://github.com/constellr/product-lst
edit_uri: https://github.com/constellr/product-lst/tree/main/docs/
nav:
  - Home: index.md
  - Demo: demo.md
 

theme:
  name: material
  favicon: assets/logo-constellr-dark-icon.svg
  logo: assets/logo-constellr-dark-icon.svg
  features:
    #- navigation.tabs
    #- navigation.top
    #- toc.integrate
    - content.tooltips

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - bibtex:
      bib_file: docs/refs.bib
      cite_style: "pandoc"
markdown_extensions:
  - footnotes
